process.env.HMR_PORT=0;process.env.HMR_HOSTNAME="localhost";parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"bzVR":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const e=require("electron");function l(){const l=e.Menu.buildFromTemplate([{label:"All Clips"},{label:"Workspace",submenu:[{label:"Workspace #1"},{label:"Workspace #2"},{label:"Workspace #3"}]}]);e.app.dock.setMenu(l),e.app.dock.show()}exports.BuildMenu=l;
},{}],"xFr5":[function(require,module,exports) {
module.exports="/network.df98324c.png";
},{}],"jrzg":[function(require,module,exports) {
"use strict";function e(){const e=__dirname.split("/");return e.splice(0,e.length-2).join("/")+"/electron-ipc.js"}Object.defineProperty(exports,"__esModule",{value:!0}),exports.GetIpcFileFixUrl=e;
},{}],"06rE":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const e=require("electron"),r=require("url"),o=require("./ipc-helper"),{resolve:t}=require("app-root-path"),n=require("electron-is-dev");function a(){const a=new e.BrowserWindow({width:300,height:200,show:!1,transparent:!0,fullscreenable:!1,vibrancy:"ultra-dark",alwaysOnTop:!0,skipTaskbar:!0,frame:!1,webPreferences:{webSecurity:!1,scrollBounce:!0,nodeIntegration:!1,preload:o.GetIpcFileFixUrl()}});a.once("ready-to-show",()=>{a.show(),a.focus()});const l=r.format({pathname:t("app/widgets/annotator/.parcel/production/index.html"),protocol:"file:",slashes:!0}),s=n?"http://localhost:1125":l;a.setMenu(null),a.loadURL(s)}exports.BuildAnnotator=a;
},{"./ipc-helper":"jrzg"}],"PTX7":[function(require,module,exports) {
"use strict";var e=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(exports,"__esModule",{value:!0});const t=require("electron"),l=e(require("../assets/network.png")),r=require("./annotator");let a=null;function o(e){const o=t.nativeImage.createFromPath(__dirname+l.default);o.resize({width:30,height:30}),(a=new t.Tray(o)).setImage(o);const i=()=>{e.isFocused()||e.focus()},c=t.Menu.buildFromTemplate([{label:"New Note",click:()=>{r.BuildAnnotator()}},{label:"All Clips",click:i},{label:"Workspace #1",click:i},{label:"Workspace #2",click:i},{label:"Workspace #3",click:i}]);a.setContextMenu(c)}exports.BuildTray=o;
},{"../assets/network.png":"xFr5","./annotator":"06rE"}],"qH2W":[function(require,module,exports) {
"use strict";var e=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var t={};if(null!=e)for(var o in e)Object.hasOwnProperty.call(e,o)&&(t[o]=e[o]);return t.default=e,t};Object.defineProperty(exports,"__esModule",{value:!0});const t=require("electron"),o=e(require("lodash"));function r(){let e=t.screen.getAllDisplays();e.filter(e=>0!==e.bounds.x||0!==e.bounds.y);console.log(e)}exports.GetExternalDisplay=r;const s=e=>{let o=e.getBounds(),r=t.screen.getDisplayNearestPoint({x:o.x,y:o.y});e.setBounds(r.bounds,!0)};exports.onMovedDebounced=o.debounce(s,200);
},{}],"a9Cf":[function(require,module,exports) {
"use strict";var e=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var r={};if(null!=e)for(var t in e)Object.hasOwnProperty.call(e,t)&&(r[t]=e[t]);return r.default=e,r};Object.defineProperty(exports,"__esModule",{value:!0});const r=require("express"),t=require("cors"),u=e(require("body-parser")),s=r();function n(e){const r={};if(e.query)for(const t in e.query)r[t]=e.query[t];return r}s.use(t()),s.use(u.urlencoded({extended:!0})),s.use(u.json()),s.get("/api/meta/",(e,r)=>{r.json({data:"AWESOME"})}),exports.default=s;
},{}],"exEY":[function(require,module,exports) {
"use strict";var e=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(exports,"__esModule",{value:!0});const r=e(require("./app")),t=require("helmet"),o=require("compression"),s=require("net");function n(e){return new Promise((r,t)=>{!function e(r,t){const o=s.createServer();o.listen(r,()=>{o.once("close",()=>{t(r)}),o.close()}),o.on("error",()=>{e(++r,t)})}(e,r)})}async function u(){r.default.use(t()),r.default.use(o()),r.default.disable("x-powered-by");const e=await n(1e3);r.default.listen(e,()=>console.log("Starting ExpressJS API server on Port 8081"));return{server:r.default,API_PORT:e}}exports.GetAPIServer=u;
},{"./app":"a9Cf"}],"ZCfc":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const e=require("./helpers/dock"),r=require("./helpers/tray"),t=require("./helpers/screen"),o=require("url"),n=require("./helpers/annotator"),i=require("./helpers/ipc-helper"),a=require("../api/server"),l=require("electron"),{BrowserWindow:s,app:c}=l,p=require("electron-is-dev"),{resolve:u}=require("app-root-path");c.on("ready",async()=>{e.BuildMenu(),c.setName("Athena Prototype");const d=l.screen.getPrimaryDisplay().size,h=new s({width:d.width,height:d.height-22,show:!1,transparent:!0,resizable:!1,fullscreenable:!1,titleBarStyle:"hidden",vibrancy:"ultra-dark",webPreferences:{webSecurity:!1,scrollBounce:!0,nodeIntegration:!1,preload:i.GetIpcFileFixUrl()}});r.BuildTray(h),h.once("ready-to-show",()=>{h.show()}),h.on("move",t.onMovedDebounced.bind(this,h));const w=o.format({pathname:u("app/renderer/.parcel/production/index.html"),protocol:"file:",slashes:!0}),y=p?"http://localhost:1124":w;h.setMenu(null),h.loadURL(y),l.ipcMain.on("launch-annotator",()=>{n.BuildAnnotator()});const q=await a.GetAPIServer();h.API_PORT=q.API_PORT}),c.on("window-all-closed",c.quit);
},{"./helpers/dock":"bzVR","./helpers/tray":"PTX7","./helpers/screen":"qH2W","./helpers/annotator":"06rE","./helpers/ipc-helper":"jrzg","../api/server":"exEY"}]},{},["ZCfc"], null)
//# sourceMappingURL=/main.js.map