process.env.HMR_PORT=0;process.env.HMR_HOSTNAME="localhost";parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"bzVR":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const e=require("electron");function l(){const l=e.Menu.buildFromTemplate([{label:"All Clips"},{label:"Workspace",submenu:[{label:"Workspace #1"},{label:"Workspace #2"},{label:"Workspace #3"}]}]);e.app.dock.setMenu(l),e.app.dock.show()}exports.BuildMenu=l;
},{}],"6beC":[function(require,module,exports) {
module.exports="/owl.34a066de.png";
},{}],"jrzg":[function(require,module,exports) {
"use strict";function e(){const e=__dirname.split("/");return e.splice(0,e.length-2).join("/")+"/electron-ipc.js"}Object.defineProperty(exports,"__esModule",{value:!0}),exports.GetIpcFileFixUrl=e;
},{}],"06rE":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const e=require("electron"),r=require("url"),o=require("./ipc-helper"),{resolve:t}=require("app-root-path"),n=require("electron-is-dev");function a(){const a=new e.BrowserWindow({width:300,height:200,show:!1,transparent:!0,fullscreenable:!1,vibrancy:"ultra-dark",alwaysOnTop:!0,skipTaskbar:!0,frame:!1,webPreferences:{webSecurity:!1,scrollBounce:!0,nodeIntegration:!1,preload:o.GetIpcFileFixUrl()}});a.once("ready-to-show",()=>{a.show(),a.focus()});const l=r.format({pathname:t("app/widgets/annotator/.parcel/production/index.html"),protocol:"file:",slashes:!0}),s=n?"http://localhost:1125":l;a.setMenu(null),a.loadURL(s)}exports.BuildAnnotator=a;
},{"./ipc-helper":"jrzg"}],"PTX7":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const e=require("electron"),l=require("../assets/owl.png"),t=require("./annotator");let r=null;function c(c){const o=e.nativeImage.createFromPath(__dirname+l);o.resize({width:30,height:30}),(r=new e.Tray(o)).setImage(o);const a=()=>{c.isFocused()||c.focus()},i=e.Menu.buildFromTemplate([{label:"New Note",click:()=>{t.BuildAnnotator()}},{label:"All Clips",click:a},{label:"Workspace #1",click:a},{label:"Workspace #2",click:a},{label:"Workspace #3",click:a}]);r.setContextMenu(i)}exports.BuildTray=c;
},{"../assets/owl.png":"6beC","./annotator":"06rE"}],"qH2W":[function(require,module,exports) {
"use strict";var e=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var t={};if(null!=e)for(var r in e)Object.hasOwnProperty.call(e,r)&&(t[r]=e[r]);return t.default=e,t};Object.defineProperty(exports,"__esModule",{value:!0});const t=require("electron"),r=e(require("lodash"));function s(){t.screen.getAllDisplays().filter(e=>0!==e.bounds.x||0!==e.bounds.y)}exports.GetExternalDisplay=s;const n=e=>{const r=e.getBounds(),s=t.screen.getDisplayNearestPoint({x:r.x,y:r.y});e.setBounds(s.bounds,!0)};exports.onMovedDebounced=r.debounce(n,200);
},{}],"a9Cf":[function(require,module,exports) {
"use strict";var e=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var r={};if(null!=e)for(var t in e)Object.hasOwnProperty.call(e,t)&&(r[t]=e[t]);return r.default=e,r};Object.defineProperty(exports,"__esModule",{value:!0});const r=require("express"),t=require("cors"),u=e(require("body-parser")),s=r();function n(e){const r={};if(e.query)for(const t in e.query)r[t]=e.query[t];return r}s.use(t()),s.use(u.urlencoded({extended:!0})),s.use(u.json()),s.get("/api/meta/",(e,r)=>{r.json({data:"AWESOME"})}),exports.default=s;
},{}],"exEY":[function(require,module,exports) {
"use strict";var e=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(exports,"__esModule",{value:!0});const r=e(require("./app")),t=require("helmet"),o=require("compression"),s=require("net");function n(e){return new Promise((r,t)=>{!function e(r,t){const o=s.createServer();o.listen(r,()=>{o.once("close",()=>{t(r)}),o.close()}),o.on("error",()=>{e(++r,t)})}(e,r)})}async function u(){r.default.use(t()),r.default.use(o()),r.default.disable("x-powered-by");const e=await n(1e3);r.default.listen(e,()=>console.log("Starting ExpressJS API server on Port 8081"));return{server:r.default,API_PORT:e}}exports.GetAPIServer=u;
},{"./app":"a9Cf"}],"OBnq":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const e=require("electron"),t=require("url"),{resolve:r}=require("app-root-path");let l;function o(){l=new e.BrowserWindow({title:"Project Athena",width:300,height:300,show:!0,transparent:!0,resizable:!1,fullscreenable:!1,titleBarStyle:"customButtonsOnHover",maximizable:!1,minimizable:!1,closable:!1,alwaysOnTop:!0,frame:!1});const o=t.format({pathname:r("build/splash.html"),protocol:"file:",slashes:!0});return l.loadURL(o),l}exports.GetSplashWindow=o;
},{}],"ZCfc":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const e=require("./helpers/dock"),r=require("./helpers/tray"),t=require("./helpers/screen"),o=require("url"),i=require("./helpers/annotator"),n=require("./helpers/ipc-helper"),l=require("../api/server"),a=require("./helpers/splash"),s=require("electron"),{BrowserWindow:c,app:u}=s,p=require("electron-is-dev"),{resolve:h}=require("app-root-path");u.on("ready",async()=>{e.BuildMenu(),u.setName("Project Athena");const d=a.GetSplashWindow(),w=s.screen.getPrimaryDisplay().size,q=new c({title:"Project Athena",width:w.width,height:w.height-22,show:!1,transparent:!0,resizable:!1,fullscreenable:!1,titleBarStyle:"hidden",vibrancy:"ultra-dark",webPreferences:{webSecurity:!1,scrollBounce:!0,nodeIntegration:!1,preload:n.GetIpcFileFixUrl()}});r.BuildTray(q),q.once("ready-to-show",()=>{setTimeout(()=>{d.destroy(),setTimeout(()=>{q.show()},30)},2e3)}),q.on("move",t.onMovedDebounced.bind(this,q));const y=o.format({pathname:h("app/renderer/.parcel/production/index.html"),protocol:"file:",slashes:!0}),P=p?"http://localhost:1124":y;q.setMenu(null),q.loadURL(P),s.ipcMain.on("launch-annotator",()=>{i.BuildAnnotator()});const b=await l.GetAPIServer();q.API_PORT=b.API_PORT}),u.on("window-all-closed",u.quit);
},{"./helpers/dock":"bzVR","./helpers/tray":"PTX7","./helpers/screen":"qH2W","./helpers/annotator":"06rE","./helpers/ipc-helper":"jrzg","../api/server":"exEY","./helpers/splash":"OBnq"}]},{},["ZCfc"], null)
//# sourceMappingURL=/main.js.map